language: python

sudo: true

python:
  - "2.7"


install:
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install decorator
  - pip install docutils
  #- gem install s3
  #- "if [[ ${BROWSER} == 'ie' ]]; then pip install ie_only_pkg; fi"

before_script:
  #- "chmod 777 ~/.ssh/known_hosts"
  #- "echo $KNOWN_HOSTS >> ~/.ssh/id_rsa.pub"
  #- "echo $SSH_KEY > /home/travis/.ssh/key"
  #- "cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  #- "today=$(date +%d.%m.%Y)"
  #- "find / -type f -perm /6000 -exec stat -c "%A %a %n" {} \"

script:
  #- "firefox --version"
  #- "python test/run_tests.py python $BROWSER --noncritical known_issue_-_travisci"
  #- "python demo/rundemo.py python $BROWSER --noncritical known_issue_-_travisci"
  #- find / -type f -perm /6000 -exec stat -c "%A %a %n" {} \;

  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD -i control2 tests/web

  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/TestPlanManagement/testPlanContent.robot
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/Layout/layout.robot
  - pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/Administration
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/testExecution/testExecution.robot

  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/testExecution/tp91_execute_test.robot
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/testExecution/testExecution.robot


  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/web/TestPlanManagement/testPlanContent/tp78_update_linked_tc_version.robot


env:
  matrix:
  - BROWSER=firefox
  #- BROWSER=ie # will be added later
  #- BROWSER=safari # will be added later

after_script:
   #- zip -r build_$today.zip /home/travis/build/marcel-veselka/testlink-qa-robot/*

   #- sed -e 's/\s\+/\n/g' ~/.ssh/key > ~/.ssh/key1
   #- echo -----BEGIN RSA PRIVATE KEY----- > /home/travis/.ssh/id_rsa
   #- cat ~/.ssh/key1 >> ~/.ssh/id_rsa
   #- echo -----END RSA PRIVATE KEY----- >> /home/travis/.ssh/id_rsa
   #- chmod 400 ~/.ssh/id_rsa
   #- chmod 600 ~/.ssh/id_rsa

   #- echo -e "Host testlab.tesena.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
   #- echo " StrictHostKeyChecking no" >> ~/.ssh/config

   #- scp -v -i ~/.ssh/id_rsa /home/travis/build/marcel-veselka/testlink-qa-robot/build_$today.zip ubuntu@testlab.tesena.com:/home/ubuntu/reports/
# todo: upload instead of individual files info s3 bucket

addons:
  artifacts:
    bucket: "tesena-s3"
    endpoint: "tesena-s3.s3-website-us-west-2.amazonaws.com"
    s3_region: "us-west-2" # defaults to "us-east-1"

#notifications:
  #email:
   # - alexandra.kolpakova@tesena.com